-- Service Atlas initial schema (§6).
--
-- Portability rule (ADR-002): this file runs unmodified on both H2 and PostgreSQL. That means
-- VARCHAR rather than TEXT/CLOB, BIGINT IDENTITY rather than SERIAL, no jsonb, and no
-- engine-specific defaults. JSON payloads are application-serialised strings.

CREATE TABLE workspace (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(200)     NOT NULL,
    root_path     VARCHAR(1000)    NOT NULL,
    settings_json VARCHAR(1000000),
    created_at    TIMESTAMP        NOT NULL,
    updated_at    TIMESTAMP        NOT NULL
);

CREATE UNIQUE INDEX ux_workspace_name ON workspace (name);

CREATE TABLE scan (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT        NOT NULL,
    status       VARCHAR(20)   NOT NULL,
    started_at   TIMESTAMP     NOT NULL,
    finished_at  TIMESTAMP,
    repo_count   INTEGER       NOT NULL DEFAULT 0,
    error_count  INTEGER       NOT NULL DEFAULT 0,
    message      VARCHAR(2000),
    CONSTRAINT fk_scan_workspace FOREIGN KEY (workspace_id) REFERENCES workspace (id) ON DELETE CASCADE
);

CREATE INDEX ix_scan_workspace ON scan (workspace_id);

-- Per-repository progress (FR-7.1), failure isolation (FR-7.2) and the content hashes that make
-- re-scans incremental (FR-7.3).
CREATE TABLE scan_repo (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_id       BIGINT        NOT NULL,
    repo_path     VARCHAR(1000) NOT NULL,
    display_name  VARCHAR(200),
    status        VARCHAR(20)   NOT NULL,
    message       VARCHAR(2000),
    content_hash  VARCHAR(64),
    duration_ms   BIGINT,
    CONSTRAINT fk_scan_repo_scan FOREIGN KEY (scan_id) REFERENCES scan (id) ON DELETE CASCADE
);

CREATE INDEX ix_scan_repo_scan ON scan_repo (scan_id);

CREATE TABLE service_node (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_id       BIGINT        NOT NULL,
    node_key      VARCHAR(400)  NOT NULL,
    display_name  VARCHAR(400)  NOT NULL,
    type          VARCHAR(20)   NOT NULL,
    framework     VARCHAR(100),
    scala_version VARCHAR(40),
    sbt_version   VARCHAR(40),
    repo_path     VARCHAR(1000),
    parent_key    VARCHAR(400),
    metadata_json VARCHAR(1000000),
    CONSTRAINT fk_service_node_scan FOREIGN KEY (scan_id) REFERENCES scan (id) ON DELETE CASCADE
);

CREATE INDEX ix_service_node_scan ON service_node (scan_id);
CREATE UNIQUE INDEX ux_service_node_scan_key ON service_node (scan_id, node_key);

CREATE TABLE dependency_edge (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_id       BIGINT        NOT NULL,
    source_key    VARCHAR(400)  NOT NULL,
    target_key    VARCHAR(400)  NOT NULL,
    edge_type     VARCHAR(20)   NOT NULL,
    confidence    VARCHAR(10)   NOT NULL,
    label         VARCHAR(400),
    evidence_json VARCHAR(1000000),
    CONSTRAINT fk_dependency_edge_scan FOREIGN KEY (scan_id) REFERENCES scan (id) ON DELETE CASCADE
);

CREATE INDEX ix_dependency_edge_scan ON dependency_edge (scan_id);

-- Manual edits and layout positions, which survive re-scans (FR-4.4, FR-5.3).
CREATE TABLE overlay (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT        NOT NULL,
    kind         VARCHAR(40)   NOT NULL,
    target_key   VARCHAR(400),
    payload_json VARCHAR(1000000) NOT NULL,
    created_at   TIMESTAMP     NOT NULL,
    CONSTRAINT fk_overlay_workspace FOREIGN KEY (workspace_id) REFERENCES workspace (id) ON DELETE CASCADE
);

CREATE INDEX ix_overlay_workspace ON overlay (workspace_id);

-- Only populated when the optional Lucid REST API export is configured (FR-6.2, Q-3).
CREATE TABLE lucid_credentials (
    workspace_id     BIGINT PRIMARY KEY,
    encrypted_tokens VARCHAR(4000) NOT NULL,
    connected_at     TIMESTAMP     NOT NULL,
    CONSTRAINT fk_lucid_credentials_workspace FOREIGN KEY (workspace_id) REFERENCES workspace (id) ON DELETE CASCADE
);
